"""add last message in channels

Revision ID: adaf22ad43c7
Revises: ce9352a93025
Create Date: 2024-11-04 11:11:38.288426

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "adaf22ad43c7"
down_revision: Union[str, None] = "ce9352a93025"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "channels", sa.Column("message_id", sa.BigInteger(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("channels", "message_id")
    # ### end Alembic commands ###
